### ISSUE TITLE
OpenCL build error with recent NVIDIA driver and older JtR: implicit conversion from address space "generic" to address space "private" is not supported

### ISSUE THREAD

**Issue by blandyuk** [openwall/john#5338]
When trying to run dmg-opencl, I get the below. Please find example hash also below also. NVIDIA driver version is 516.94.

[Hash]
https://paste.blandyuk.co.uk/c9NwiyUR

[Compile Error]
Device 3: NVIDIA GeForce RTX 2080 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL])
Cost 1 (iteration count) is 128205 for all loaded hashes
Cost 2 (version) is 2 for all loaded hashes
Options used: -I run/kernels -cl-mad-enable -DSM_MAJOR=7 -DSM_MINOR=5 -D__GPU__ -DDEVICE_INFO=1048594 -D__SIZEOF_HOST_SIZE_T__=8 -DDEV_VER_MAJOR=516 -DDEV_VER_MINOR=94 -D_OPENCL_COMPILER -DHASH_LOOPS=500 -DOUTLEN=32 -DV_WIDTH=1 run/kernels/dmg_kernel.cl
Build log: <kernel>:112:21: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
        hmac_sha1(key, 20, (const uchar*)&cno, 4, iv, 20);
                           ^~~~~~~~~~~~~~~~~~
run/kernels\opencl_hmac_sha1.h:28:43: note: passing argument to parameter '_data' here
                      HMAC_MSG_TYPE void *_data, uint data_len,
                                          ^
<kernel>:117:31: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
        AES_cbc_decrypt(salt->chunk, outbuf, salt->data_size, &aes_decrypt_key, iv);
                                     ^~~~~~
run/kernels\opencl_aes.h:159:60: note: passing argument to parameter '_out' here
AES_cbc_decrypt(AES_SRC_TYPE void *_in, AES_DST_TYPE void *_out,
                                                           ^
<kernel>:127:22: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
                hmac_sha1(key, 20, (const uchar*)&cno, 4, iv, 20);
                                   ^~~~~~~~~~~~~~~~~~
run/kernels\opencl_hmac_sha1.h:28:43: note: passing argument to parameter '_data' here
                      HMAC_MSG_TYPE void *_data, uint data_len,
                                          ^
<kernel>:132:33: error: implicit conversion from address space "generic" to address space "private" is not supported when passing to parameter of destination type
                AES_cbc_decrypt(salt->zchunk, outbuf, 4096, &aes_decrypt_key, iv);
                                              ^~~~~~
run/kernels\opencl_aes.h:159:60: note: passing argument to parameter '_out' here
AES_cbc_decrypt(AES_SRC_TYPE void *_in, AES_DST_TYPE void *_out,
                                                           ^

Error building kernel run/kernels/dmg_kernel.cl. DEVICE_INFO=1048594
0: OpenCL CL_BUILD_PROGRAM_FAILURE (-11) error in opencl_common.c:1386 - clBuildProgram

**Comment by ghost** [comment]
Thanks for reporting.

Could you please confirm that you are using an updated version of John the Ripper?

I would say this has been fixed at https://github.com/openwall/john/pull/4669.

**Comment by blandyuk** [comment]
Just downloaded latest version, still happens. Sorry, forgot to mention I'm on Win10. Had to copy the OpenCL.dll to the john "run" folder also and rename, as the default does not work at all.

Also just installed older CUDA Drivers "cuda_11.3.1_465.89_win10" to test, still fails.

**Comment by ghost** [comment]
**[edited]**

Please note that the latest is something showing `bleeding` and `2023` (as seen below):

```
$ john
John the Ripper 1.9.0-jumbo-1+bleeding-2ad75ba45f 2023-06-25 21:48:00 +0200 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2022 by Solar Designer and others
```
In other words, I hope you are using the latest version of this repository instead of Jumbo 1.

Anyway, we will investigate.

**Comment by blandyuk** [comment]
I copied the latest kernel "dmg_kernel.cl" and problem persists. Last changed 2 years ago. magnum does say "Problems seen with nvidia 465.xx.", so I'll get older driver version and try.

**Comment by ghost** [comment]
In fact, the headers are the offending files (in this case).

**Comment by blandyuk** [comment]
I've pushed back to "cuda_11.2.2_461.33_win10" and it's working now. Seems there is something breaking it.

I'll download latest jumbo and make it on Linux. Presume this will create Win executables also.

**Comment by ghost** [comment]
If you need updated Windows executables, download https://github.com/openwall/john-packages/releases/download/jumbo-dev/winX64_1_JtR.7z

**Comment by solardiz** [comment]
Of course, you'll be getting these errors with our older Windows build when you have new CUDA, and simply replacing one kernel's source isn't expected to help - IIRC, our fix was to pass an extra option during OpenCL build, which we did from the main program's code.

> I'll download latest jumbo and make it on Linux. Presume this will create Win executables also.

No, it won't create a Windows build. You can use one Claudio referenced instead.

See also #5205, #5222, #5319, and most importantly this workaround: https://github.com/openwall/john/issues/5222#issuecomment-1364355009

**Comment by solardiz** [comment]
> I would say this has been fixed at #4669.

No, the problem appeared later than that and I think it was fixed in #5207.

I'll close this issue now since it's not something we need to track, but it's a useful reminder for us that people are indeed running into already-fixed issues when using our previous release, and that we should make a new release.

**Comment by blandyuk** [comment]
OK thanks both. Just needed that latest build it seems. I'll test and get back to you. Thanks for the great help as always.

I did not find the below link. Maybe link it on the john website, so we can find it easier?

https://github.com/openwall/john-packages/releases/

**Comment by blandyuk** [comment]
OK, well might have to open this again as it's still failing, but different issue now.

CUDA Driver used: cuda_11.8.0_522.06_windows
Latest john: [John the Ripper dev pack 20230626.1]

john process starts, but just hangs and does nothing. Any ideas? It did start once, but was 0% GPU util, nothing:

Device 3: NVIDIA GeForce RTX 2080 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL])
Cost 1 (iteration count) is 128205 for all loaded hashes
Cost 2 (version) is 2 for all loaded hashes
LWS=64 GWS=139264 (2176 blocks)
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
0g 0:00:00:13 0.03% (ETA: 07:23:00) 0g/s 0p/s 0c/s 0C/s
Remaining hashes    1 (0 removed)
Remaining salts     1 (0 removed)
Time in seconds     13.09 (13.09 new)
Successful guesses  0 (0 new, 0 g/s)
Passwords tested    0 (0 new, 0 p/s)
 dupe suppressor    is disabled
 and it accepted    0 (0.00%, 0 p/s)
        rejected    0 (0.00%, 0 p/s)
    out of total    0 (0 p/s)
Hash computations   0 (0 new, 0 c/s)
Hash combinations   0 (0 new, 0 C/s)

**Comment by solardiz** [comment]
@blandyuk Per your edited comment, looks like it's working now? 13 seconds is just too little for results (even statistics) to start showing up for something as slow as DMG at 100k+ iterations, at a GWS as high as this.

Other than that, I suggest clearing NVIDIA's cache when you change John versions as you might end up with inconsistencies otherwise (there's detection of changes to main kernel source files, but not of other source files they `#include`, so a change only in the latter might not trigger a rebuild). On Linux, you'd `rm -rf ~/.nv/ComputeCache`. I don't know what the equivalent of `~/.nv/ComputeCache` is on Windows.

**Comment by ghost** [comment]
Thinking the Windows way of life:
* install the recently downloaded `john` in a new folder
* or remove the old folder and unzip new `john` using the same folder name
* reboot after installing or removing system software like drivers
* Stuff like that
* allow the antivirus do its job
* and be patient

**Comment by solardiz** [comment]
@claudioandre-br Stuff like that, but I guess there's still a separate NVIDIA compute cache directory to be cleaned up manually, ideally. I think we usually dodge that bullet by also making changes to main kernel files between releases, but if someone upgrades between "adjacent" two of your builds, they might very well run into the issue of not having the kernel rebuilt where expected. Usually that would mean a missed performance optimization or a missed bug fix (and not worse than that), because for incompatible changes to included files there's generally a corresponding change to the kernel as well. But there might be exceptions, unless we identify and deliberately make main kernel file changes (even if dummy changes) in all such cases.

**Comment by blandyuk** [comment]
It took over 3 minutes to even get to the status part. I waited longer than 13 secs, 0% GPU util.

**Comment by solardiz** [comment]
@blandyuk OK, but does it run fine now, showing non-zero statistics if you leave it running for some minutes more? Does it also take over 3 minutes to get to the status if you re-run the command? You can add the `-v=5` option to see verbose output on what it's doing.

**Comment by ghost** [comment]
> @claudioandre-br Stuff like that, but I guess there's still a separate NVIDIA compute cache directory to be cleaned up manually,

It should be at `%APPDATA\%NVIDIA\ComputeCache`. 

However, timestamps change if you recreate files (and I hope this is a tip for NVIDIA). Can anyone test and check for us? All `.cl` files should be:
* Modified: 2023-07-26 21:09
* Accessed: today (I mean, the "installation" day).

@blandyuk, could you please confirm this?

**Comment by blandyuk** [comment]
ComputeCache purged. Here is the result below. The old version with the old driver worked perfect. I get ~23000-24000 C/s with 3x RTX 2080 Ti. Below is just using one for testing as not working:

Device 3: NVIDIA GeForce RTX 2080 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL])
Cost 1 (iteration count) is 128205 for all loaded hashes
Cost 2 (version) is 2 for all loaded hashes
LWS=64 GWS=278528 (4352 blocks)
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
0g 0:00:03:16 0.05% (ETA: 2023-07-18 03:25) 0g/s 0p/s 0c/s 0C/s
Remaining hashes    1 (0 removed)
Remaining salts     1 (0 removed)
Time in seconds     196.24 (196.24 new)
Successful guesses  0 (0 new, 0 g/s)
Passwords tested    0 (0 new, 0 p/s)
 dupe suppressor    is disabled
 and it accepted    0 (0.00%, 0 p/s)
        rejected    0 (0.00%, 0 p/s)
    out of total    0 (0 p/s)
Hash computations   0 (0 new, 0 c/s)
Hash combinations   0 (0 new, 0 C/s)

![image](https://github.com/openwall/john/assets/22078464/5625b749-fd6e-4add-84dc-d6504e20f987)

**Comment by solardiz** [comment]
@blandyuk This is puzzling. Please open a new issue for this. Please also show what happens on `--test --format=dmg-opencl` and whether other formats work for you. Thank you!

**Comment by ghost** [comment]
Posting here because I'm on Windows and can't wait here. It works on AMD, at least.

Test case is {"$dmg$2*20*dc39029a22b86bb4f9304995[...] from  CMIYC 2012

```powershell
C:\Users\claud\jul-10\JtR>run\john --test --format=dmg-opencl
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL]... LWS=128 GWS=4096 (32 blocks) DONE
Speed for cost 1 (iteration count) of 1000, cost 2 (version) of 2 and 1
Raw:    70389 c/s real, 1032K c/s virtual
```


```powershell
C:\Users\claud\jul-10\JtR>run\john --format=dmg-opencl \Temp\hash.txt
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
Using default input encoding: UTF-8
Loaded 1 password hash (dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL])
Cost 1 (iteration count) is 1000 for all loaded hashes
Cost 2 (version) is 2 for all loaded hashes
LWS=64 GWS=4096 (64 blocks)
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:run/password.lst
Enabling duplicate candidate password suppressor
654321           (?)
1g 0:00:00:00 DONE 2/3 (2023-07-13 18:53) 3.012g/s 12337p/s 12337c/s 12337C/s 123456..bob123
Use the "--show" option to display all of the cracked passwords reliably
Session completed.
```

Now using the same hash you are using:
```powershell
C:\Users\claud\jul-10\JtR>run\john --format=dmg-opencl \Users\claud\Downloads\paste_230713182243.txt --max-run=60
Device 1: gfx902 [AMD Radeon(TM) Vega 8 Graphics]
Using default input encoding: UTF-8
Loaded 1 password hash (dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL])
Cost 1 (iteration count) is 128205 for all loaded hashes
Cost 2 (version) is 2 for all loaded hashes
LWS=64 GWS=4096 (64 blocks)
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:run/password.lst
Enabling duplicate candidate password suppressor
Device 1 probably invalid temp reading (-1°C).
0g 0:00:01:03 0.00% 2/3 (ETA: 2023-09-28 23:54) 0g/s 773.7p/s 773.7c/s 773.7C/s hardcore!..080190
Session stopped (max run-time reached)
```
*****
**[edited]**

You should use a lower GWS, 139264 looks like is a huge number. What about a 16384. Play a little bit with it.
```
set GWS=16384
run\john ....
```

Your GPU is 10 times faster than mine, but your GWS value is 35 times higher.

Also, please add verbosity to one of your tests `run\john.exe --test --format=dmg-opencl --verb=6`. One explanation is bad autotune behavior.

**Comment by blandyuk** [comment]
It took awhile to do, but it worked:

run\john.exe--test --format=dmg-opencl

Device 3: NVIDIA GeForce RTX 2080 Ti
Benchmarking: dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL]... LWS=128 GWS=139264 (1088 blocks) DONE
Speed for cost 1 (iteration count) of 1000, cost 2 (version) of 2 and 1
Raw:    693315 c/s real, 1364K c/s virtual

@claudioandre-br your second test was CPU only, just letting you know. Try it with opencl.

**Comment by solardiz** [comment]
@blandyuk OK, so only actual cracking gets stuck. Are you able to use any other format, without it getting stuck like that?

**Comment by ghost** [comment]
Sorry, I told I had to go back to work. I amended to the previous comment.

**Comment by blandyuk** [comment]
OK, tested a bcrypt hash, works OK:

Device 3: NVIDIA GeForce RTX 2080 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (bcrypt-opencl [Blowfish OpenCL])
Cost 1 (iteration count) is 1024 for all loaded hashes
LWS=8 GWS=4096 (512 blocks)
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status

0g 0:00:00:28 0.00% (ETA: 2023-07-21 01:43) 0g/s 872.1p/s 872.1c/s 872.1C/s 1354745082..20463374
Remaining hashes    1 (0 removed)
Remaining salts     1 (0 removed)
Time in seconds     28.18 (18.79 new)
Successful guesses  0 (0 new, 0 g/s)
Passwords tested    24576 (16384 new, 872.1 p/s)
 dupe suppressor    is disabled
 and it accepted    0 (0.00%, 0 p/s)
        rejected    0 (0.00%, 0 p/s)
    out of total    0 (0 p/s)
Hash computations   24576 (16384 new, 872.1 c/s)
Hash combinations   24576 (16384 new, 872.1 C/s)

**Comment by solardiz** [comment]
@blandyuk For testing, can you try your `dmg-opencl` cracking run (that would get stuck) with a lower GWS, like `--gws=34816`?

**Comment by blandyuk** [comment]
Sure, here is the result below. Took awhile to start again:

C:\Cracking\JtR_2023-06>run\john.exe "--format=dmg-opencl" --gws=34816 hashes.txt --wordlist=..\rockyou.txt
Device 3: NVIDIA GeForce RTX 2080 Ti
Using default input encoding: UTF-8
Loaded 1 password hash (dmg-opencl, Apple DMG [PBKDF2-SHA1 3DES/AES OpenCL])
Cost 1 (iteration count) is 128205 for all loaded hashes
Cost 2 (version) is 2 for all loaded hashes
LWS=256 GWS=34816 (136 blocks)
Press 'q' or Ctrl-C to abort, 'h' for help, almost any other key for status

0g 0:00:01:25 0.01% (ETA: 2023-07-31 05:54) 0g/s 0p/s 0c/s 0C/s
Remaining hashes    1 (0 removed)
Remaining salts     1 (0 removed)
Time in seconds     85.23 (77.74 new)
Successful guesses  0 (0 new, 0 g/s)
Passwords tested    0 (0 new, 0 p/s)
 dupe suppressor    is disabled
 and it accepted    0 (0.00%, 0 p/s)
        rejected    0 (0.00%, 0 p/s)
    out of total    0 (0 p/s)
Hash computations   0 (0 new, 0 c/s)
Hash combinations   0 (0 new, 0 C/s)

**Comment by solardiz** [comment]
@blandyuk OK. That's weird. Can you test `pbkdf2-hmac-sha1-opencl` with this input:

```
$pbkdf2-hmac-sha1$128205$6926d45e$231c561018a4cee662df7cd4a8206701c5806af9
```

Regarding the slow start, add `-v=5` to see what it's doing during that time.

**Comment by blandyuk** [comment]
OK, here is the -v=5 output for "format=dmg-opencl":

https://paste.blandyuk.co.uk/6Qh95KQA

Here is the john PBKDF2-HMAC-SHA1-opencl output below. It started way quicker and works:

https://paste.blandyuk.co.uk/Uwxtt00n

**Comment by solardiz** [comment]
@blandyuk OK, can you please open a separate issue for this? Describe that cracking a certain "hash" with `dmg-opencl` gets stuck at 0% GPU utilization (right?), but cracking a same iteration count PBKDF2-HMAC-SHA1-opencl hash works. Thank you!

**Comment by blandyuk** [comment]
Create a new issue cheers :)

https://github.com/openwall/john/issues/5341

UPDATE: Sorry, please close mine as noticed @claudioandre-br created one already.
